# Generated by Django 4.2.6 on 2023-10-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=32, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=64, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('category', models.SmallIntegerField(choices=[(1, 'Office'), (2, '3C'), (3, 'Real Estate')], verbose_name='Category')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='FK_Department')),
            ],
        ),
    ]
